### ISSUE TITLE
The system cannot find the path specified

### ISSUE THREAD

**Issue by kanakiyajay** [krampstudio/grunt-jsdoc#124]
I am on Windows 7 x64 and have installed jsdoc globally using and grunt-jsdoc locally

`npm install grunt-jsdoc@beta --save-dev`
`npm install -g jsdoc@"<=3.3.0"`

Here's the gruntfile for the project copied from the Readme
Gruntfile.js

```js
module.exports = function(grunt) {

  require('load-grunt-tasks')(grunt);

  grunt.initConfig({
      jsdoc : {
        dist : {
            src: ['src/*.js', 'test/*.js'],
            options: {
                destination: 'doc'
            }
        }
    }
});

  grunt.registerTask('default', ['jsdoc']);
};
```

Here's the output on running jsdoc with verbose and debug
```
$ grunt --verbose jsdoc --debug
Initializing
Command-line options: --verbose, --debug=1

Reading "Gruntfile.js" Gruntfile...OK

Registering Gruntfile tasks.

Registering "grunt-jsdoc" local Npm module tasks.
Reading H:\grunt-tasks.com\github\14-grunt-jsdoc\node_modules\grunt-jsdoc\package.json...OK
Parsing H:\grunt-tasks.com\github\14-grunt-jsdoc\node_modules\grunt-jsdoc\package.json...OK
Loading "jsdoc-plugin.js" tasks...OK
+ jsdoc
Initializing config...OK
Loading "Gruntfile.js" tasks...OK
+ default

Running tasks: jsdoc

Running "jsdoc" task
[D] Task source: H:\grunt-tasks.com\github\14-grunt-jsdoc\node_modules\grunt-jsdoc\tasks\jsdoc-plugin.
js

Running "jsdoc:dist" (jsdoc) task
[D] Task source: H:\grunt-tasks.com\github\14-grunt-jsdoc\node_modules\grunt-jsdoc\tasks\jsdoc-plugin.
js
Verifying property jsdoc.dist exists in config...OK
Files: src/area.js
Options: private, destination="doc"
[D] { private: true, destination: 'doc' }
[D] Using jsdoc from : node_modules\grunt-jsdoc\node_modules\.bin\jsdoc
[D] Reading option: private
[D] Reading option: destination
[D]                 > doc
[D] Running : cmd /c node_modules\grunt-jsdoc\node_modules\.bin\jsdoc --private --destination doc src/
area.js
>> An error occurs in jsdoc process:
>> The system cannot find the path specified.
Warning: jsdoc failure Use --force to continue.

Aborted due to warnings.
```

I have tried it using Windows cmd and cygwin.

From the error and warning messages it not able to find the path.
It will be great if you can help to resolve this error.

**Comment by kanakiyajay** [comment]
Update:

On running:

`jsdoc --private --destination doc src/area.js`

It throws the following error

```
js: "C:/Users/Kanakiya/AppData/Roaming/npm/node_modules/jsdoc/jsdoc.js", line 316: exception from uncaught JavaScript throw: Error: ENOENT, no such file or directory 'src/area.js
```

But on running using absolute paths 
`jsdoc --private --destination doc h:/grunt-tasks.com/github/14-grunt-jsdoc/src/area.js`

It doesn't throw any error but doesn't documentation as well.

**Comment by krampstudio** [comment]
I think this one should be solved now. Could you confirm ?

**Comment by kanakiyajay** [comment]
I have updated grunt-jsdoc to 1.1, but it still gives an error

```
Initializing
Command-line options: --verbose, --debug=1

Reading "Gruntfile.js" Gruntfile...OK

Registering Gruntfile tasks.

Registering "grunt-jsdoc" local Npm module tasks.
Reading H:\grunt-tasks.com\github\14-grunt-jsdoc-ng\node_modules\grunt-jsdoc\package.json...OK
Parsing H:\grunt-tasks.com\github\14-grunt-jsdoc-ng\node_modules\grunt-jsdoc\package.json...OK
Loading "jsdoc-plugin.js" tasks...OK
+ jsdoc
Initializing config...OK
Loading "Gruntfile.js" tasks...OK
+ default

Running tasks: jsdoc

Running "jsdoc" task
[D] Task source: H:\grunt-tasks.com\github\14-grunt-jsdoc-ng\node_modules\grunt-jsdoc\tasks\jsdoc-plugin.js

Running "jsdoc:dist" (jsdoc) task
[D] Task source: H:\grunt-tasks.com\github\14-grunt-jsdoc-ng\node_modules\grunt-jsdoc\tasks\jsdoc-plugin.js
Verifying property jsdoc.dist exists in config...OK
Files: src/area.js
Options: private, ignoreWarnings=false, timeout=60, destination="doc"
[D] Using jsdoc from : node_modules\grunt-jsdoc\node_modules\.bin\jsdoc
[D] Running : cmd /c node_modules\grunt-jsdoc\node_modules\.bin\jsdoc --destination doc --private src/area.js
>> The system cannot find the path specified.
Warning: jsdoc terminated with a non-zero exit code Use --force to continue.

Aborted due to warnings.

Kanakiya@Kanakiya-HP ~/grunt-tasks.com/github/14-grunt-jsdoc-ng
$ npm install -g jsdoc
C:\Users\Kanakiya\AppData\Roaming\npm\jsdoc -> C:\Users\Kanakiya\AppData\Roaming\npm\node_modules\jsdoc\jsdoc.js
npm WARN unmet dependency C:\Users\Kanakiya\AppData\Roaming\npm\node_modules\ionic\node_modules\unzip\node_modules\pullstream requires readable-stream@'~1.0.0' but will load
npm WARN unmet dependency C:\Users\Kanakiya\AppData\Roaming\npm\node_modules\ionic\node_modules\unzip\node_modules\readable-stream,
npm WARN unmet dependency which is version 1.0.26-2
npm WARN unmet dependency C:\Users\Kanakiya\AppData\Roaming\npm\node_modules\ionic\node_modules\unzip\node_modules\match-stream requires readable-stream@'~1.0.0' but will load
npm WARN unmet dependency C:\Users\Kanakiya\AppData\Roaming\npm\node_modules\ionic\node_modules\unzip\node_modules\readable-stream,
npm WARN unmet dependency which is version 1.0.26-2
npm WARN unmet dependency C:\Users\Kanakiya\AppData\Roaming\npm\node_modules\ionic\node_modules\unzip\node_modules\pullstream\node_modules\slice-stream requires readable-stream@'~1.0.2' but will load
npm WARN unmet dependency C:\Users\Kanakiya\AppData\Roaming\npm\node_modules\ionic\node_modules\unzip\node_modules\readable-stream,
npm WARN unmet dependency which is version 1.0.26-2
npm WARN unmet dependency C:\Users\Kanakiya\AppData\Roaming\npm\node_modules\phonegap\node_modules\phonegap-build requires colors@'0.6.x' but will load
npm WARN unmet dependency C:\Users\Kanakiya\AppData\Roaming\npm\node_modules\phonegap\node_modules\colors,
npm WARN unmet dependency which is version 0.6.0-1
npm WARN unmet dependency C:\Users\Kanakiya\AppData\Roaming\npm\node_modules\phonegap\node_modules\prompt\node_modules\winston requires colors@'0.x.x' but will load
npm WARN unmet dependency C:\Users\Kanakiya\AppData\Roaming\npm\node_modules\phonegap\node_modules\colors,
npm WARN unmet dependency which is version 0.6.0-1
jsdoc@3.4.0 C:\Users\Kanakiya\AppData\Roaming\npm\node_modules\jsdoc
├── escape-string-regexp@1.0.3
├── strip-json-comments@1.0.4
├── async@1.4.2
├── taffydb@2.6.2
├── underscore@1.8.3
├── marked@0.3.5
├── wrench@1.5.8
├── js2xmlparser@1.0.0
├── requizzle@0.2.1 (underscore@1.6.0)
├── espree@2.2.5
├── bluebird@2.9.34
└── catharsis@0.8.7 (underscore-contrib@0.3.0)

Kanakiya@Kanakiya-HP ~/grunt-tasks.com/github/14-grunt-jsdoc-ng
$ grunt --verbose jsdoc --debug
Initializing
Command-line options: --verbose, --debug=1

Reading "Gruntfile.js" Gruntfile...OK

Registering Gruntfile tasks.

Registering "grunt-jsdoc" local Npm module tasks.
Reading H:\grunt-tasks.com\github\14-grunt-jsdoc-ng\node_modules\grunt-jsdoc\package.json...OK
Parsing H:\grunt-tasks.com\github\14-grunt-jsdoc-ng\node_modules\grunt-jsdoc\package.json...OK
Loading "jsdoc-plugin.js" tasks...OK
+ jsdoc
Initializing config...OK
Loading "Gruntfile.js" tasks...OK
+ default

Running tasks: jsdoc

Running "jsdoc" task
[D] Task source: H:\grunt-tasks.com\github\14-grunt-jsdoc-ng\node_modules\grunt-jsdoc\tasks\jsdoc-plugin.js

Running "jsdoc:dist" (jsdoc) task
[D] Task source: H:\grunt-tasks.com\github\14-grunt-jsdoc-ng\node_modules\grunt-jsdoc\tasks\jsdoc-plugin.js
Verifying property jsdoc.dist exists in config...OK
Files: src/area.js
Options: private, ignoreWarnings=false, timeout=60, destination="doc"
[D] Using jsdoc from : node_modules\grunt-jsdoc\node_modules\.bin\jsdoc
[D] Running : cmd /c node_modules\grunt-jsdoc\node_modules\.bin\jsdoc --destination doc --private src/area.js
>> The system cannot find the path specified.
Warning: jsdoc terminated with a non-zero exit code Use --force to continue.

Aborted due to warnings.
```

The issue is still how it generates the path, its trying `src/area.js` when in windows it should be absolute.

**Comment by krampstudio** [comment]
Could you please test with version 2.0.0 ?

**Comment by krampstudio** [comment]
any update ?

**Comment by kanakiyajay** [comment]
It worked. :-) 

FYI, here is the output it generated -

`grunt --verbose jsdoc --debug`

```
Initializing
Command-line options: --verbose, --debug=1

Reading "Gruntfile.js" Gruntfile...OK

Registering Gruntfile tasks.

Registering "grunt-jsdoc" local Npm module tasks.
Reading H:\grunt-tasks.com\github\14-grunt-jsdoc-ng\node_modules\grunt-jsdoc\package.json...OK
Parsing H:\grunt-tasks.com\github\14-grunt-jsdoc-ng\node_modules\grunt-jsdoc\package.json...OK
Loading "jsdoc-plugin.js" tasks...OK
+ jsdoc
Initializing config...OK
Loading "Gruntfile.js" tasks...OK
+ default

Running tasks: jsdoc

Running "jsdoc" task
[D] Task source: H:\grunt-tasks.com\github\14-grunt-jsdoc-ng\node_modules\grunt-jsdoc\tasks\jsdoc-plugin.js

Running "jsdoc:dist" (jsdoc) task
[D] Task source: H:\grunt-tasks.com\github\14-grunt-jsdoc-ng\node_modules\grunt-jsdoc\tasks\jsdoc-plugin.js
Verifying property jsdoc.dist exists in config...OK
Files: src/area.js
Options: ignoreWarnings=false, timeout=60, destination="doc"
[D] Using jsdoc from : node_modules\grunt-jsdoc\node_modules\.bin\jsdoc
[D] Running : node_modules\grunt-jsdoc\node_modules\.bin\jsdoc --destination doc src/area.js
Documentation generated to H:\grunt-tasks.com\github\14-grunt-jsdoc-ng\doc
Done, without errors.
```

**Comment by krampstudio** [comment]
cool!
